version: "3.9"

services:
  client:
    build:
      context: ./client
      args:
        # pass host API root so React knows where to fetch
        REACT_APP_API_ROOT: http://localhost:8000
    ports:
      - "3000:80"
    restart: unless-stopped
